# Generated by Django 6.0.3 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoLogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trivia', 'Trivia'), ('adivinanza', 'Adivinanza'), ('rompecabezas', 'Rompecabezas'), ('paradoja', 'Paradoja')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='La pregunta o descripción del contenido')),
                ('respuesta', models.TextField(help_text='La respuesta correcta o explicación')),
                ('opciones', models.JSONField(blank=True, help_text="Para trivias: listas de opciones ['A', 'B', 'C']", null=True)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contenido Lógico',
                'verbose_name_plural': 'Contenidos Lógicos',
            },
        ),
    ]
