# Generated by Django 6.0.3 on 2026-04-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='logica.contenidologico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'unique_together': {('usuario', 'contenido')},
            },
        ),
    ]
