# Generated by Django 6.0.3 on 2026-04-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='comentario_docente',
            field=models.TextField(blank=True, help_text='Comentarios de retroalimentación del docente', null=True),
        ),
    ]
