# Generated by Django 6.0.3 on 2026-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_resolucion_comentario_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidologico',
            name='imagen',
            field=models.FileField(blank=True, help_text='Imagen para el rompecabezas', null=True, upload_to='logica/'),
        ),
    ]
