# Generated by Django 6.0.5 on 2026-05-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_contenidologico_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_logica', models.CharField(choices=[('proposicional', 'Lógica Proposicional'), ('predicados', 'Lógica de Predicados'), ('inferencia', 'Inferencia y Demostración'), ('conjuntos', 'Teoría de Conjuntos'), ('boole', 'Álgebra de Boole'), ('general', 'General')], default='general', max_length=50)),
                ('preguntas', models.JSONField(help_text='Lista de preguntas: [{"pregunta": "...", "opciones": ["A","B","C","D"], "respuesta_correcta": "A"}]')),
                ('umbral_aprobacion', models.IntegerField(default=60, help_text='Porcentaje mínimo para aprobar (ej: 60)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Respuestas del estudiante: {"0": "A", "1": "C", ...}')),
                ('puntaje', models.IntegerField(help_text='Cantidad de respuestas correctas')),
                ('total_preguntas', models.IntegerField()),
                ('aprobado', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='logica.evaluacion')),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación',
                'verbose_name_plural': 'Resultados de Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
