# Generated by Django 6.0.5 on 2026-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0005_evaluacion_resultadoevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidologico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Habilitado/Deshabilitado para los estudiantes'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='historial_intentos',
            field=models.JSONField(blank=True, default=list, help_text='Historial detallado de intentos'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='intentos',
            field=models.IntegerField(default=1, help_text='Cantidad de intentos realizados'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='tiempo_usado',
            field=models.IntegerField(default=0, help_text='Tiempo total utilizado en segundos'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='tiempo_usado',
            field=models.IntegerField(default=0, help_text='Tiempo utilizado en segundos'),
        ),
    ]
