# Generated by Django 6.0.3 on 2026-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_verified_alter_usuario_area_estudios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=20),
        ),
    ]
