# Generated by Django 6.0.3 on 2026-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
