# Generated by Django 6.0.5 on 2026-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seccion',
            field=models.CharField(blank=True, default='Sección A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10, null=True),
        ),
    ]
