# Generated by Django 6.0.3 on 2026-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10),
        ),
    ]
